### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Tamila-Bodnar** [Tamila-Bodnar/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Vlad-of** [comment]
"Change is an opportunity in disguise"

Javascript web developer. I like to solve problems in building websites and web applications that are responsive, accessible, and have a great user experience using HTML, CSS, SCSS, JavaScript, Gul, DOM, jQuery, React, APIs, Github, and other technologies. Additionally, I want to know and use back-end technologies such as Node.js, Express.js, PostgreSQL, GraphQL.

 And now keywords to get past the bots 🤖:
Javascript (ES6+), React, Typescript, npm, Node.js, git, Agile Software Development,  Adobe PhotoShop.
