### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Tamila-Bodnar** [Tamila-Bodnar/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Vlad-of** [comment]
tamila.bodnar@gmail.com
LinkedIn: https://www.linkedin.com/in/tamila-bodnar/
Skype: tamila.bodnar
