### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Tamila-Bodnar** [Tamila-Bodnar/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Vlad-of** [comment]
August 2019-Present - Traffic Lite CPA, HTML/CSS coder (building landing pages, adaptive design, work with Adobe Photoshop)
April 2019-Present - Freelance, Junior Front-end Developer (building landing pages, blocks, forms, taking part in projects with HTML, CSS, JavaScript, JQuery)
May 2013 – March 2019 - Service for Children Vinnytsia Regional State Administration, chief specialist (security administrator  information-analytical program “Deti”, implementation of the reform of the institutional care system and upbringing of children in the region, training of employees of services for children from the region, analyzing information, organizing events, support of the web pages)
October 2012 - May 2013 - Vinnytsia regional municipal shelter for children “Dobro”, teacher (pedagogical work)
2010 - 2011 - ІТ “RIA.UA” (auto.ria.ua), an account manager (customer service, support of the web site)
2007 - 2004 - The Organization “KMT-Agro”, office manager (customer service, documentation)
2004 - 2003 - The Affiliated Organization “Konditer” of the Organization “Gamma”, sales representative (customer service, increase in sales, promotion distribution)
2002 - 2003 - The Affiliated Organization “Konditer” of the Organization “Gamma”, operative (customer service, consultant by phone)

  Education
1999 - 2004  Vinnytsia State Pedagogical University named after Mykhailo Kotsiubynsky, Institute of mathematics, physics and technological education, specialization “Mathematics and Information Technologies” (full-time studies)
1990 - 1999  Vinnytsia Physics and Mathematics Gymnasium 17

**Comment by Tamila-Bodnar** [comment]
Thanks!
